<a href="https://colab.research.google.com/github/dkapadia1/musicAI/blob/main/Copy_of_MusicGen_Gradio_Demo_v1_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MusicGen Gradio Demo

Execute the first cell to install, the second one to run the demo.

More info on our repository [facebookresearch/audiocraft](https://github.com/facebookresearch/audiocraft/) or our [research paper](https://arxiv.org/abs/2306.05284).

First eval with a model will be slower because of the model download. Melody model should take 30 seconds for 15 seconds of audio.

In [ ]:
!python -m pip install -U audiocraft

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 635.7/635.7 kB 7.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.9/32.9 MB 31.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.4/72.4 kB 10.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 22.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.3/143.3 kB 21.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 71.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.8

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
# prompt: load the encodec model and torchaudio
from audiocraft.models import CompressionModel

from torchaudio import load

# Load the Encodec model
model = CompressionModel.get_pretrained('facebook/encodec_32khz')
audio, sr = load('/content/drive/MyDrive/music/#FREEUNKY.mp3')
# Load an audio file

audio = audio[:, :5 * sr]
print(audio.shape)
print(sr)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/236M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
/usr/local/lib/python3.10/dist-packages/transformers/models/encodec/modeling_encodec.py:120: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer("padding_total", torch.tensor(kernel_size - stride, dtype=torch.int64), persistent=False)


torch.Size([2, 240000])
48000


In [ ]:
mono_audio = audio[0]

In [ ]:
from transformers import AutoProcessor
processor = AutoProcessor.from_pretrained("facebook/encodec_32khz")
inputs = processor(raw_audio=mono_audio, sampling_rate=processor.sampling_rate, return_tensors="pt")


preprocessor_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [ ]:
# Encode the audio
encoding = model.encode(mono_audio[None].expand(3, -1, -1))


In [ ]:
if encoding[1] is None:
    encoding = encoding[0]

In [ ]:
print(encoding)
#Embedding perchance?
tens = model.decode_latent(encoding)

tensor([[[ 778, 1019, 1721,  ...,  237,  658,  247],
         [1725,  825, 1719,  ..., 1583, 1632, 2025],
         [1235, 1385,  629,  ..., 1899, 1600,  213],
         [1898, 1379, 1595,  ..., 1873,  664,  341]],

        [[ 778, 1019, 1721,  ...,  237,  658,  247],
         [1725,  825, 1719,  ..., 1583, 1632, 2025],
         [1235, 1385,  629,  ..., 1899, 1600,  213],
         [1898, 1379, 1595,  ..., 1873,  664,  341]],

        [[ 778, 1019, 1721,  ...,  237,  658,  247],
         [1725,  825, 1719,  ..., 1583, 1632, 2025],
         [1235, 1385,  629,  ..., 1899, 1600,  213],
         [1898, 1379, 1595,  ..., 1873,  664,  341]]])


In [ ]:
print(tens.shape)
print(tens)

torch.Size([3, 128, 375])
tensor([[[ 5.4942,  2.7355,  0.9807,  ...,  0.2359, -1.5911,  2.8904],
         [ 2.1795, -1.2976, -1.1501,  ..., -0.5467, -2.0811,  1.4545],
         [-6.1171,  3.1768,  7.4195,  ..., -4.6023, -1.7351, -3.1011],
         ...,
         [ 0.1603, -0.5473,  0.7079,  ...,  1.6784, -0.9420,  0.8927],
         [-1.4711,  0.6377, -1.6899,  ..., -2.5770,  0.9013, -1.6948],
         [ 2.2744, -2.5097, -4.4478,  ...,  1.1124,  0.3776,  3.0040]],

        [[ 5.4942,  2.7355,  0.9807,  ...,  0.2359, -1.5911,  2.8904],
         [ 2.1795, -1.2976, -1.1501,  ..., -0.5467, -2.0811,  1.4545],
         [-6.1171,  3.1768,  7.4195,  ..., -4.6023, -1.7351, -3.1011],
         ...,
         [ 0.1603, -0.5473,  0.7079,  ...,  1.6784, -0.9420,  0.8927],
         [-1.4711,  0.6377, -1.6899,  ..., -2.5770,  0.9013, -1.6948],
         [ 2.2744, -2.5097, -4.4478,  ...,  1.1124,  0.3776,  3.0040]],

        [[ 5.4942,  2.7355,  0.9807,  ...,  0.2359, -1.5911,  2.8904],
         [ 2.1795, 

In [ ]:
audio, sr = load('/content/drive/MyDrive/music/#FREEUNKY.mp3')
audio2 = audio[:, 5 * sr:10 * sr]
mono_audio2 = audio2[0]
print(mono_audio2.shape)
encoding2 = model.encode(mono_audio2[None].expand(3, -1, -1))
if encoding2[1] is None:
    encoding2 = encoding2[0]
else:
  #throw an error
  raise Exception("error")

tens2 = model.decode_latent(encoding2)

print(tens2.shape)
print(tens2)



torch.Size([240000])
torch.Size([3, 128, 375])
tensor([[[ 4.3617,  2.1554, -0.8051,  ...,  0.1812, -2.6474,  2.6907],
         [-1.8387, -1.2910, -1.2079,  ..., -2.0759, -2.9832,  1.2339],
         [ 2.7337, -3.2436, -0.5973,  ..., -0.8375, -0.5463,  1.1924],
         ...,
         [-1.7679, -0.2226,  1.3877,  ..., -1.4410, -0.7930, -1.1639],
         [ 2.1781,  1.9039,  2.1166,  ...,  0.0703,  1.0720,  1.9930],
         [ 1.0937, -0.9723,  1.8769,  ...,  0.0381,  1.1519, -3.5082]],

        [[ 4.3617,  2.1554, -0.8051,  ...,  0.1812, -2.6474,  2.6907],
         [-1.8387, -1.2910, -1.2079,  ..., -2.0759, -2.9832,  1.2339],
         [ 2.7337, -3.2436, -0.5973,  ..., -0.8375, -0.5463,  1.1924],
         ...,
         [-1.7679, -0.2226,  1.3877,  ..., -1.4410, -0.7930, -1.1639],
         [ 2.1781,  1.9039,  2.1166,  ...,  0.0703,  1.0720,  1.9930],
         [ 1.0937, -0.9723,  1.8769,  ...,  0.0381,  1.1519, -3.5082]],

        [[ 4.3617,  2.1554, -0.8051,  ...,  0.1812, -2.6474,  2.6907]

In [ ]:
import torchaudio
# prompt: define a function that takes in a audio file location and returns the latent decoding of the audio file simlar to the cell above
resampler = torchaudio.transforms.Resample(orig_freq=sr, new_freq=32000)
def get_latent_decoding(audio_file_location, seconds = 5):
  """
  Takes in an audio file location and returns the latent decoding of the audio file.

  Args:
      audio_file_location: The location of the audio file.

  Returns:
      The latent decoding of the audio file.
  """
  # Load the audio file
  audio, sr = load(audio_file_location)
  # Resample the audio to 32000 Hz
  audio = resampler(audio)
  # Trim the audio to the desired length
  audio = audio[:, :seconds * 32000]
  mono_audio = audio[0]
  # Encode the audio
  encoding = model.encode(mono_audio[None].expand(3, -1, -1))

  if encoding[1] is None:
      encoding = encoding[0]

  tens = model.decode_latent(encoding)

  return tens


In [ ]:
# prompt: compare the two 3d tensors and return some similarity metric(tens and tens2)

import torch
#tensor dimension are 3, 128, 375
# Calculate the cosine similarity between the two tensors.
similarity = torch.nn.functional.cosine_similarity(tens, tens2, dim=1)

# Print the similarity metric.
print(similarity[0].sum())
def get_similarity(tens, tens2):
  """
  Takes in two 3d tensors and returns the cosine similarity between them.

  Args:
      tens: The first tensor.
      tens2: The second tensor.

  Returns:
      The cosine similarity between the two tensors.
  """
  # Calculate the cosine similarity between the two tensors.
  similarity = torch.nn.functional.cosine_similarity(tens, tens2, dim=1)

  # Print the similarity metric.
  return(similarity[0].sum())

tensor(68.1631)


In [ ]:
#take 2 different music files and check their "similarity" idk if this cosine similar sum means anyhting
unktens = get_latent_decoding('/content/drive/MyDrive/music/#FREEUNKY.mp3')
ovrtens = get_latent_decoding('/content/drive/MyDrive/music/100 OVR.mp3')
print(unktens.shape)
print(ovrtens.shape)
get_similarity(unktens, ovrtens)


torch.Size([3, 128, 375])
torch.Size([3, 128, 375])


tensor(85.7781)

In [ ]:
def get_similarity_file(file1, file2, seconds = 5):
  """
  Takes in two audio file locations and returns the cosine similarity between them.

  Args:
      file1: The first audio file location.
      file2: The second audio file location.

  Returns:
      The cosine similarity between the two audio files.
      """
      #get the latent decoding of the file
  tens1 = get_latent_decoding(file1, seconds = seconds)
  tens2 = get_latent_decoding(file2, seconds = seconds)
    #get the similarity
  return get_similarity(tens1, tens2)
#

In [ ]:
import os
import time
firsttrack = '/content/drive/MyDrive/music/#FREEUNKY.mp3'
distances = []
i = 0
#loop through all the files in the folder
for file in os.listdir('/content/drive/MyDrive/music/'):
  ctime = time.time()
  if i > 100:
    break
  else:
    i += 1
  if file.endswith('.mp3'):
    #print(file)
    distances.append((get_similarity_file(firsttrack, '/content/drive/MyDrive/music/' + file), file))
    print(time.time() - ctime, "seconds", file)
#sort distances by similarity
distances.sort(key=lambda x: x[0])
print(distances[-1])
#

15.669291019439697 seconds Shelley FKA DRAM - Crumbs (feat. Playboi Carti) [Official Audio].mp3
12.040215969085693 seconds Playboi Carti - dothatshit! (Audio).mp3
13.166861534118652 seconds Playboi Carti - Lame Niggaz (Audio).mp3
13.986737728118896 seconds Playboi Carti - Other Shit (Audio).mp3
11.376407384872437 seconds Playboi Carti - Had 2 (Audio).mp3
11.143826723098755 seconds Mileage.mp3
11.714433670043945 seconds Top.mp3
11.657850503921509 seconds Home (KOD).mp3
9.556273221969604 seconds Pull Up.mp3
11.334965705871582 seconds Lean 4 Real.mp3
10.517992496490479 seconds Foreign.mp3
8.917012929916382 seconds Middle Of The Summer.mp3
10.795091152191162 seconds R.I.P. Fredo (Notice Me).mp3
9.356813907623291 seconds Playboi Carti - Yah Mean (Official Audio).mp3


RuntimeError: The size of tensor a (375) must match the size of tensor b (345) at non-singleton dimension 2

In [ ]:
riptens = get_latent_decoding('/content/drive/MyDrive/music/Playboi Carti - R.I.P..mp3', seconds = 5)
print(riptens.shape)

torch.Size([3, 128, 345])


In [ ]:
audio, sr = load('/content/drive/MyDrive/music/Playboi Carti - R.I.P..mp3')
print(audio.shape)
print(sr)
audio2, sr2 = load('/content/drive/MyDrive/music/#FREEUNKY.mp3')
print(audio2.shape)
print(sr2)

torch.Size([2, 8327168])
44100
torch.Size([2, 8765210])
48000


In [ ]:
#sort distances by similarity
distances.sort(key=lambda x: x[0])
print(distances[-1])

(tensor(51.4883), 'Playboi Carti - Had 2 (Audio).mp3')
